MODRM_VARIANT_REG = 'reg'
MODRM_VARIANT_ATREG = 'atreg'
MODRM_VARIANT_ATDISP32 = 'atdisp32'
MODRM_VARIANT_ATREGPLUSDISP8 = 'atregplusdisp8'
MODRM_VARIANT_ATREGPLUSDISP32 = 'atregplusdisp32'
MODRM_VARIANT_ATSCALEINDEXBASE = 'atscaleindexbase'
MODRM_VARIANT_ATSCALEINDEXBASEDISP8 = 'atscaleindexbasedisp8'
MODRM_VARIANT_ATSCALEINDEXBASEDISP32 = 'atscaleindexbasedisp32'

ARCH_I386 = 'i386'
ARCH_AMD64 = 'amd64'

arch_variants = (ARCH_I386, ARCH_AMD64)

PARAMETER_SEPARATOR = ',\n  '

modrm_variants = (
    MODRM_VARIANT_REG,
    MODRM_VARIANT_ATREG,
    MODRM_VARIANT_ATDISP32,
    MODRM_VARIANT_ATREGPLUSDISP8,
    MODRM_VARIANT_ATREGPLUSDISP32,
    MODRM_VARIANT_ATSCALEINDEXBASE,
    MODRM_VARIANT_ATSCALEINDEXBASEDISP8,
    MODRM_VARIANT_ATSCALEINDEXBASEDISP32,
)

CGEN_OUTPUT_COMPONENT_SEPARATOR = ',\n    '
CGEN_PARAMETER_SEPARATOR = ',\n  '

possible_reg_operands = {
    'reg8': 8,
    'reg16': 16,
    'reg32': 32,
    'reg64': 64
}

possible_regmem_operands = {
    'reg/mem8': 8,
    'reg/mem16': 16,
    'reg/mem32': 32,
    'reg/mem64': 64
}

PREFIX = 'X86GEN'
